<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SPTushonka.Reflection</AssemblyName>
    <RootNamespace>SPTushonka.Reflection</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>$(BepInExCore)/Il2CppInterop.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Diz.Jobs">
      <HintPath>$(Interop)/Diz.Jobs.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
